// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed assets/icon/kitten_icon.ico
var resourceKitteniconIcoData []byte
var resourceKitteniconIco = &fyne.StaticResource{
	StaticName:    "assets/icon/kitten_icon.ico",
	StaticContent: resourceKitteniconIcoData,
}

//go:embed assets/fonts/Nunito-Regular.ttf
var resourceNunitoRegularTtfData []byte
var resourceNunitoRegularTtf = &fyne.StaticResource{
	StaticName:    "assets/fonts/Nunito-Regular.ttf",
	StaticContent: resourceNunitoRegularTtfData,
}

//go:embed assets/images/kitten_greet.png
var resourceKittengreetPngData []byte
var resourceKittengreetPng = &fyne.StaticResource{
	StaticName:    "assets/images/kitten_greet.png",
	StaticContent: resourceKittengreetPngData,
}
